import React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { Analytics } from "@vercel/analytics/next"
import Script from "next/script"
import "./globals.css"

const _geist = Geist({ subsets: ["latin"] })
const _geistMono = Geist_Mono({ subsets: ["latin"] })

export const metadata: Metadata = {
  metadataBase: new URL("https://www.tigerfax.com"),
  title: {
    default: "TigerFax — Send & Receive Faxes from Your iPhone",
    template: "%s | TigerFax",
  },
  description:
    "The modern fax app for iPhone and iPad. Scan documents, add cover pages, and send real faxes worldwide. Pro users get a dedicated US fax number and inbox. Start free — no credit card required.",
  keywords: [
    "fax app",
    "iPhone fax",
    "send fax from phone",
    "mobile fax",
    "fax from iPhone",
    "TigerFax",
    "iOS fax app",
    "receive fax",
    "fax number",
    "fax app for iPhone",
    "send fax from iPad",
    "online fax",
  ],
  authors: [{ name: "TigerFax" }],
  creator: "TigerFax",
  publisher: "TigerFax",
  category: "Productivity",
  openGraph: {
    title: "TigerFax — Send & Receive Faxes from Your iPhone",
    description:
      "Scan documents, add cover pages, and send real faxes worldwide. Pro users get a dedicated US fax number and inbox.",
    type: "website",
    locale: "en_US",
    url: "https://www.tigerfax.com",
    siteName: "TigerFax",
    // OG image is auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "TigerFax — Send & Receive Faxes from Your iPhone",
    description:
      "The modern fax app for iPhone. Start free with 3 pages — no credit card required.",
    // Twitter image is auto-generated by app/opengraph-image.tsx
  },
  icons: {
    icon: [
      {
        url: "/favicon.ico",
        sizes: "any",
      },
      {
        url: "/icon-light-32x32.png",
        sizes: "32x32",
        type: "image/png",
        media: "(prefers-color-scheme: light)",
      },
      {
        url: "/icon-dark-32x32.png",
        sizes: "32x32",
        type: "image/png",
        media: "(prefers-color-scheme: dark)",
      },
      {
        url: "/icon.svg",
        type: "image/svg+xml",
      },
    ],
    shortcut: "/favicon.ico",
    apple: "/apple-icon.png",
  },
  alternates: {
    canonical: "https://www.tigerfax.com",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
}

// JSON-LD Structured Data
const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "TigerFax",
  url: "https://www.tigerfax.com",
  logo: "https://www.tigerfax.com/images/gemini-generated-image-ieqesaieqesaieqe.png",
  contactPoint: {
    "@type": "ContactPoint",
    email: "support@tigerfax.com",
    contactType: "customer support",
  },
  sameAs: [],
}

const softwareAppSchema = {
  "@context": "https://schema.org",
  "@type": "MobileApplication",
  name: "TigerFax",
  operatingSystem: "iOS",
  applicationCategory: "BusinessApplication",
  offers: [
    {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
      description: "Free plan — 3 pages included",
    },
    {
      "@type": "Offer",
      price: "4.99",
      priceCurrency: "USD",
      description: "Pro plan — dedicated fax number, unlimited inbox",
    },
  ],
  description:
    "The modern fax app for iPhone and iPad. Scan documents, add cover pages, and send real faxes worldwide. Pro users get a dedicated US fax number and inbox.",
  url: "https://www.tigerfax.com",
  downloadUrl: "https://apps.apple.com/us/app/tigerfax/id6758597882",
  screenshot: [
    "https://www.tigerfax.com/images/main_screen.PNG",
    "https://www.tigerfax.com/images/fax_inbox.PNG",
    "https://www.tigerfax.com/images/fax_usage.PNG",
  ],
}

const websiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "TigerFax",
  url: "https://www.tigerfax.com",
  potentialAction: {
    "@type": "SearchAction",
    target: {
      "@type": "EntryPoint",
      urlTemplate: "https://www.tigerfax.com/support",
    },
    "query-input": "required name=search_term_string",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="font-sans antialiased">
        {children}
        <Analytics />
        {/* Structured Data */}
        <Script
          id="schema-organization"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
        />
        <Script
          id="schema-software-app"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareAppSchema) }}
        />
        <Script
          id="schema-website"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
        />
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-T882GYJW25"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-T882GYJW25');
          `}
        </Script>
      </body>
    </html>
  )
}
